# Generated by Django 4.2.7 on 2025-10-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('issue_created', 'Issue Created'), ('issue_updated', 'Issue Updated'), ('issue_resolved', 'Issue Resolved'), ('comment_added', 'Comment Added'), ('upvote_received', 'Upvote Received')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_issue_update', models.BooleanField(default=True)),
                ('email_on_comment', models.BooleanField(default=True)),
                ('email_on_resolution', models.BooleanField(default=True)),
                ('push_on_issue_update', models.BooleanField(default=True)),
                ('push_on_comment', models.BooleanField(default=False)),
                ('push_on_resolution', models.BooleanField(default=True)),
            ],
        ),
    ]
